# Generated by Django 5.1 on 2024-10-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquriForFranchasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invester_name', models.TextField(max_length=50)),
                ('Phone_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('City', models.TextField(max_length=240)),
                ('Locations_are_you_oppening', models.TextField(max_length=400)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        
    ]
