# Generated by Django 5.1 on 2024-10-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SG', '0003_menucard'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dish_images/'),
        ),
    ]
