# Generated by Django 4.1.13 on 2024-12-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SG', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
